name: neuro_vision_mobile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  another_flushbar: ^1.10.28
  google_fonts: ^4.0.4
  http: ^0.13.4
  provider: ^6.0.2
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.2.6
  firebase_core: 2.13.0
  firebase_auth: ^4.6.1
  cloud_firestore: 4.7.1
  uuid: 3.0.7
  intl: 0.18.1
  flutter_launcher_icons: 0.13.1
  geolocator: ^9.0.2
  easy_image_viewer: 1.2.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - lib/assets/images/
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/logo.png"

