name: neuro_vision_mobile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  another_flushbar: ^1.10.28
  google_fonts: ^4.0.4
  http: ^0.13.4
  provider: ^6.0.2
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.2.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - lib/assets/images/
  uses-material-design: true

